### ISSUE TITLE
Would it be possible for you to make the Voron 2.4 Pro CAD model available for us to download?

### ISSUE THREAD

**Issue by VitorOM** [FYSETC/FYSETC-VORON-2.4-R2-Pro#2]
Would it be possible for you to make the Voron 2.4 Pro CAD model available for us to download?

@Hoganzen 
@RichardTHF 
@eliwong 

As it is a different model from the original Voron 2.4, it would be of great help in assembly and modifications.

**Comment by Hoganzen** [comment]
Hello, I have uploaded the CAD file.

**Comment by VitorOM** [comment]
> Hello, I have uploaded the CAD file.

Thanks a lot!
