### ISSUE TITLE
Cannot find tutorial for CNC Parts Kit V2.0

### ISSUE THREAD

**Issue by VORONENTHUSIAST** [FYSETC/FYSETC-VORON-2.4-R2-Pro#3]
I bought your CNC V2.0 Parts Kit from Aliexpress - it said there was a tutorial to follow for installation, where is it?

Thanks

**Comment by jinhong-** [comment]
Heya, i am not sure if there is a different 2.0 CNC kit but this is the one i followed
https://www.youtube.com/watch?v=xVdmxemSPT4

**Comment by YoungHillionaire** [comment]
it does not show how to install the z drive joints
documentation are lacking and very poor

**Comment by VORONENTHUSIAST** [comment]
> Heya, i am not sure if there is a different 2.0 CNC kit but this is the one i followed https://www.youtube.com/watch?v=xVdmxemSPT4

Thanks that really helped actually! I've left it sat for a few days due to work and everything but only have the Z drive units left to go, everything else is built and installed on the printer.



> it does not show how to install the z drive joints documentation are lacking and very poor

From looking at the Z drive units, you don't need a tutorial for those...

**Comment by Grpwomble** [comment]
i’ve been searching for four days and even contacted the manufacturer. This video is exactly what I have. Thank you so much. Saved me a headache. It’s perfect and thank you again.

**Comment by hensenx** [comment]
Add this link (and lcd video as well) to readme.md, since this is the repository you're sharing with customers. Makes for a much better experience!
